source "http://rubygems.org"

gem "i18n"
gem "activesupport", "~> 3.0.0rc"
gem "RedCloth"
gem "maruku"
gem "rack", "~> 1.2.1"
gem "sinatra"
gem "warden"
gem "sinatra_more"
gem "ratpack"
gem "haml"
gem "broadway"
gem "json"
gem "insightful"